# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "🔒"
    
  # Python dependencies - backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "🔒"
    
  # Python dependencies - northflank services
  - package-ecosystem: "pip"
    directory: "/northflank-migration/memory-agent"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "🔒"
      
  - package-ecosystem: "pip"
    directory: "/northflank-migration/voice-agent"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "🔒"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "🔒"
