services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spiralogic-oracle
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    restart: unless-stopped
