FROM node:20-alpine
WORKDIR /app

# Install dependencies for Apple Silicon compatibility
RUN apk add --no-cache libc6-compat

ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm","run","start"]