services:
  - type: web
    name: oracle-frontend
    env: static
    buildCommand: cd oracle-frontend && npm ci && npm run build
    staticPublishPath: oracle-frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_VERSION
        value: 8