# Sesame CSM Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  log_level: "info"

model:
  name: "facebook/blenderbot-1B-distill"
  path: "/app/models/sesame"
  cache_dir: "/app/cache"
  torch_dtype: "auto"
  device_map: "auto"

generation:
  max_tokens: 150
  temperature: 0.7
  top_p: 0.9
  do_sample: true

health_check:
  enabled: true
  endpoint: "/health"
