version: "3.9"
services:
  sesame-csm:
    build:
      context: .
      dockerfile: Dockerfile.sesame
    container_name: sesame-csm
    ports:
      - "8000:8000"
    volumes:
      - ./models/sesame:/models/sesame
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s