name: Secret Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    name: Scan for API keys and secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Scan for OpenAI API keys
      run: |
        if git grep -r "sk-[a-zA-Z0-9]\{20,\}" -- ':(exclude).github/' ':(exclude)*.template' ':(exclude)*.example'; then
          echo "❌ Found OpenAI API key pattern in repository!"
          echo "Please remove API keys and use environment variables or templates instead."
          exit 1
        fi

    - name: Scan for Anthropic API keys
      run: |
        if git grep -r "sk-ant-api[0-9]\{2\}-[a-zA-Z0-9_-]\{95\}" -- ':(exclude).github/' ':(exclude)*.template' ':(exclude)*.example'; then
          echo "❌ Found Anthropic API key pattern in repository!"
          echo "Please remove API keys and use environment variables or templates instead."
          exit 1
        fi

    - name: Scan for ElevenLabs API keys
      run: |
        if git grep -r "sk_[a-f0-9]\{32\}" -- ':(exclude).github/' ':(exclude)*.template' ':(exclude)*.example'; then
          echo "❌ Found ElevenLabs API key pattern in repository!"
          echo "Please remove API keys and use environment variables or templates instead."
          exit 1
        fi

    - name: Scan for JWT secrets (long strings)
      run: |
        if git grep -r "[a-f0-9]\{128,\}" -- ':(exclude).github/' ':(exclude)*.template' ':(exclude)*.example'; then
          echo "❌ Found potential JWT secret or long hex string in repository!"
          echo "Please remove secrets and use secure random generation instead."
          exit 1
        fi

    - name: Scan for common secret patterns
      run: |
        # Check for various secret patterns
        PATTERNS=(
          "OPENAI_API_KEY=sk-"
          "ANTHROPIC_API_KEY=sk-ant"
          "ELEVENLABS_API_KEY=sk_"
          "password.*['\"][^'\"]{10,}['\"]"
          "secret.*['\"][^'\"]{20,}['\"]"
          "token.*['\"][^'\"]{20,}['\"]"
        )
        
        for pattern in "${PATTERNS[@]}"; do
          if git grep -rE "$pattern" -- ':(exclude).github/' ':(exclude)*.template' ':(exclude)*.example' ':(exclude)*.md'; then
            echo "❌ Found potential secret pattern: $pattern"
            echo "Please remove secrets and use templates or environment variables instead."
            exit 1
          fi
        done

    - name: Success message
      run: |
        echo "✅ No API keys or secrets detected in repository!"
        echo "✅ Safe to proceed with commit/merge."