name: Soullab Smoke Tests

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Newman globally
        run: npm install -g newman

      - name: Run Smoke Tests against Staging
        if: github.event_name == 'pull_request'
        run: |
          newman run tests/postman/soullab-smoke-tests.postman_collection.json \
            --env-var "BASE_URL=${{ secrets.STAGING_URL || 'https://spiralogic-oracle-staging.vercel.app' }}" \
            --reporters cli,json \
            --reporter-json-export newman-results.json

      - name: Run Smoke Tests against Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          newman run tests/postman/soullab-smoke-tests.postman_collection.json \
            --env-var "BASE_URL=${{ secrets.PRODUCTION_URL || 'https://spiralogic-oracle.vercel.app' }}" \
            --reporters cli,json \
            --reporter-json-export newman-results.json

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-results
          path: newman-results.json

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Smoke tests failed! Check the workflow run for details.'
            })